bot:
  automerge: true
travis:
  secure:
    BINSTAR_TOKEN: z1do0ZrGnEoYf1Htl5bLwRqkqKVoaOUO7MeLsFXzdL/XgH6gDYZ9nLCywhbPZyNOr/EqjJKcXo2Lt9q0FhJzInT+CHOd7BZJi3M/Y2B0YrRyL53K+lgMcmedgXQnXJLiXsNUSmrAvY2/FW0DE3ENyFf3/xz8yECC3q39VyU+ekhA9EfcebzH6QRpUGpZhqx9iOZ3wbOU8U2AZRxV3FYSklCXVKjzG2UPSBZ8ZontAsKsC63IxZjKKCNfFlPGvsWZhVxuJbDefA2Z/m7Asg3G615Gwc1zasJiwkC8hlzhncy3t8a3nfeTjTji2J6uUyZ0oEW7nLho4Nh7WKq6JQ33qypEE9rBIVEIIK9Dfd9/K0nlZq2tf8qGvJimRaNQd1K5XFeU5VoeEohS5g4qBrUxyh+0lokQYdkc41BdN4dwgY7QfSjkLW0lyb4/1kXHO6p34ZNJG0bnEug68lUEbBNNDmm2B5qG3Ykk8ngP3ds4whywngQlCpe3m6O4Hc2x3JdNMc6CV6fho1NpyYid0oZCuJ97dDoBT+Su7BHnXb0nhs4Yq38e2EbRA2mmaWLKm7yjSXZAedVZZzwyyYHwxEe8vOXq0L7KJf1SULPnJF5Yxu6fQbz3uWBNPuGOZcoIiiWp6zS39HhOfswTsJtiz1muT6LgZl2MzzPc/dslyIx4iww=
conda_forge_output_validation: true
